import { useState } from "react";
import styles from "./IaCOutput.module.css";

// Tabs differ by format
const TERRAFORM_TABS = [
  { key: "mainTf",      label: "main.tf" },
  { key: "variablesTf", label: "variables.tf" },
  { key: "outputsTf",   label: "outputs.tf" },
];

const CFN_TABS = [
  { key: "templateYaml", label: "template.yaml" },
];

export default function IaCOutput({ iac, onReset }) {
  const isCfn = iac.format === "cloudformation";
  const TABS = isCfn ? CFN_TABS : TERRAFORM_TABS;

  const [activeTab, setActiveTab] = useState(TABS[0].key);
  const [copied, setCopied] = useState(false);

  const currentContent = iac[activeTab] || "";

  function handleCopy() {
    navigator.clipboard.writeText(currentContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleDownloadCurrent() {
    const name = TABS.find((t) => t.key === activeTab)?.label || "output.tf";
    download(name, currentContent);
  }

  function handleDownloadAll() {
    if (isCfn) {
      download("template.yaml", iac.templateYaml || "");
    } else {
      download("main.tf",      iac.mainTf      || "");
      download("variables.tf", iac.variablesTf || "");
      download("outputs.tf",   iac.outputsTf   || "");
    }
  }

  function download(name, content) {
    if (!content) return;
    const blob = new Blob([content], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href = url; a.download = name; a.click();
    URL.revokeObjectURL(url);
  }

  const formatLabel = isCfn ? "CloudFormation" : "Terraform";
  const formatIcon  = isCfn ? "☁️" : "🏗";

  return (
    <div className={styles.wrapper}>
      {/* Top bar */}
      <div className={styles.topBar}>
        <div>
          <h2 className={styles.title}>
            {formatIcon} {formatLabel} Generated
          </h2>
          {iac.summary && <p className={styles.summary}>{iac.summary}</p>}
        </div>
        <div className={styles.topActions}>
          {iac.confidence > 0 && (
            <div className={styles.confidence}>
              <span className={styles.confLabel}>Confidence</span>
              <span className={styles.confValue}>{iac.confidence}%</span>
            </div>
          )}
          <button className={styles.resetBtn} onClick={onReset}>← Start Over</button>
        </div>
      </div>

      {/* What this solves */}
      <div className={styles.solveBanner}>
        <span>✅</span>
        <span>
          This {formatLabel} template was generated by scanning your codebase — no manual
          infrastructure scripting required. Review, customise, and deploy.
        </span>
      </div>

      {/* Code panel */}
      <div className={styles.outputPanel}>
        <div className={styles.panelHeader}>
          <div className={styles.fileTabs}>
            {TABS.map((t) => (
              <button
                key={t.key}
                className={activeTab === t.key ? styles.fileTabActive : styles.fileTab}
                onClick={() => setActiveTab(t.key)}
              >
                {t.label}
              </button>
            ))}
          </div>
          <div className={styles.actions}>
            <button className={styles.actionBtn} onClick={handleCopy}>
              {copied ? "✓ Copied" : "Copy"}
            </button>
            <button className={styles.actionBtn} onClick={handleDownloadCurrent}>
              ↓ This file
            </button>
            <button className={styles.actionBtnPrimary} onClick={handleDownloadAll}>
              ↓ Download All
            </button>
          </div>
        </div>

        <pre className={styles.codeBlock}>
          <code>{currentContent || `# No content generated for this file`}</code>
        </pre>
      </div>
    </div>
  );
}
